# Generated by Django 5.1.4 on 2025-01-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_remove_project_created_at_remove_project_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='experience',
            new_name='about_you',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='your_DP_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
