# Generated by Django 5.1.4 on 2025-01-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_description_post_content_post_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
