# Generated by Django 5.1.5 on 2025-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="demo_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="source_code_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Separate tags with commas", max_length=255
            ),
        ),
    ]
