# Generated by Django 5.1.4 on 2025-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Portfolio', 'Portfolio'), ('Project', 'Project'), ('Certificate', 'Certificate')], default='uncategorized', max_length=50),
            preserve_default=False,
        ),
    ]
